class Product {
  final String id;
  final String name;
  final String subtitle;
  final double price;
  final String category;
  final String subCategory;
  final String imageUrl; // Can be 'assets/images/xxx.jpg' OR 'https://...'
  final String? badge;
  final double rating;
  final String description;
  final List<String> colors;
  final List<String> sizes;

  const Product({
    required this.id,
    required this.name,
    required this.subtitle,
    required this.price,
    required this.category,
    this.subCategory = '',
    required this.imageUrl,
    this.badge,
    this.rating = 4.8,
    this.description = '',
    this.colors = const [],
    this.sizes = const [],
  });

  bool get isLocalImage =>
      imageUrl.startsWith('assets/') && !imageUrl.startsWith('http');
}

class CartItem {
  final Product product;
  int quantity;
  String selectedSize;
  String selectedColor;

  CartItem({
    required this.product,
    this.quantity = 1,
    this.selectedSize = 'M',
    this.selectedColor = 'Deep Plum',
  });

  double get total => product.price * quantity;
}

class OrderHistoryItem {
  final String orderId;
  final String productName;
  final String date;
  final double price;
  final String status;
  final String imageUrl;

  const OrderHistoryItem({
    required this.orderId,
    required this.productName,
    required this.date,
    required this.price,
    required this.status,
    required this.imageUrl,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW PRODUCT (it auto-appears in all correct category filters):
//
//   Simply add a new Product entry to allProducts below with:
//     • category    → 'Men' | 'Women' | 'Accessories'
//     • subCategory → the filter tab name, e.g. 'Trousers', 'Dresses', 'Bags'
//
//   The subcategory chip is created AUTOMATICALLY from this field.
//   No changes needed in any screen or widget file.
//
//   Men subCategories    : 'Suits' | 'Shirts' | 'Trousers' | 'Shoes'  (or add new ones)
//   Women subCategories  : 'Dresses' | 'Outerwear' | 'Footwear' | 'Tops'
//   Accessories          : 'Bags' | 'Watches' | 'Scarves' | 'Belts'
//
// HOW TO ADD YOUR OWN PRODUCT IMAGES:
//   1. Place image files in:  assets/images/
//   2. Set imageUrl to:  'assets/images/filename.jpg'
//   Example:
//     imageUrl: 'assets/images/violet_gown.jpg',
// ─────────────────────────────────────────────────────────────────────────────

final List<Product> allProducts = [

  // ── Women › Dresses ───────────────────────────────────────────────────
  const Product(
    id: 'w_d1',
    name: "Violet Atelier Gown",
    subtitle: "Limited Edition",
    price: 189.99,
    category: "Women",
    subCategory: "Dresses",
    imageUrl: "assets/images/woman/Dress/violet.jpg",
    badge: "NEW",
    rating: 4.9,
    description: "A masterclass in editorial tailoring. Structured silk-blend gown with a nipped-in waist, hand-finished in our signature Atelier Violet hue.",
    colors: ['#3D1F8C', '#C4A8E0', '#D1D5DB'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_d2',
    name: "Silk Violet Slip Dress",
    subtitle: "Color: Lavender",
    price: 49.99,
    category: "Women",
    subCategory: "Dresses",
    imageUrl: "assets/images/woman/Dress/silk violet slip dress.webp",
    rating: 4.8,
    description: "Effortless elegance in pure silk. This slip dress drapes beautifully for any occasion.",
    colors: ['#3D1F8C', '#C4A8E0'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_d3',
    name: "Cerise Shirt-Dress",
    subtitle: "Chambray Collection",
    price: 59.99,
    category: "Women",
    subCategory: "Dresses",
    imageUrl: "assets/images/woman/Dress/Cerise Shirt-dress In Chambray.jpg",
    rating: 4.7,
    description: "Relaxed shirt-dress crafted in lightweight chambray. Perfect for warm days and evening outings.",
    colors: ['#BE185D', '#D1D5DB'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_d4',
    name: "Cropped Summer Shirt Dress",
    subtitle: "Resort Wear",
    price: 39.99,
    category: "Women",
    subCategory: "Dresses",
    imageUrl: "assets/images/woman/Dress/Cropped Summer Shirt -.webp",
    rating: 4.6,
    description: "Breezy cropped shirt-dress for the modern woman. A summer wardrobe essential.",
    colors: ['#FDE68A', '#D1D5DB'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_d5',
    name: "Evening Gown Classic",
    subtitle: "Heritage Edition",
    price: 79.99,
    category: "Women",
    subCategory: "Dresses",
    imageUrl: "assets/images/woman/Dress/images.jpg",
    rating: 4.8,
    description: "Timeless evening gown silhouette. An iconic piece from our heritage collection.",
    colors: ['#1F2937', '#C4A8E0'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),

  // ── Women › Tops ──────────────────────────────────────────────────────
  const Product(
    id: 'w_t1',
    name: "Atelier Silk-Wool Blazer",
    subtitle: "Single-Breasted",
    price: 129.99,
    category: "Women",
    subCategory: "Tops",
    imageUrl: "assets/images/woman/TOP/Buy Atelier Silk-Wool Single-Breasted.webp",
    badge: "NEW",
    rating: 4.9,
    description: "Structured silk-wool blazer with exaggerated shoulders and nipped-in waist. Hand-finished.",
    colors: ['#3D1F8C', '#C4A8E0', '#D1D5DB'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_t2',
    name: "Silk Wrap Top",
    subtitle: "Long Sleeves",
    price: 54.99,
    category: "Women",
    subCategory: "Tops",
    imageUrl: "assets/images/woman/TOP/Silk Wrap Top Women - Silk Top Long Sleeves.jpg",
    rating: 4.8,
    description: "Lightweight pure silk wrap top with long sleeves. Effortlessly elegant for every season.",
    colors: ['#C4A8E0', '#D1D5DB'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_t3',
    name: "Linen Relaxed Top",
    subtitle: "Spring Collection",
    price: 34.99,
    category: "Women",
    subCategory: "Tops",
    imageUrl: "assets/images/woman/TOP/Stylish Women's Linen Tops.webp",
    rating: 4.6,
    description: "Breathable linen top in a relaxed silhouette. Ideal for warm-weather styling.",
    colors: ['#D1D5DB', '#FDE68A'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'w_t4',
    name: "Cropped Hoodie Top",
    subtitle: "Street Luxe",
    price: 29.99,
    category: "Women",
    subCategory: "Tops",
    imageUrl: "assets/images/woman/TOP/Womens Cute Crop Top Teen Girls Cropped Hoodie.jpg",
    rating: 4.5,
    description: "Soft cropped hoodie with a contemporary fit. Casual luxury for everyday wear.",
    colors: ['#9CA3AF', '#F3F4F6'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),

  // ── Women › Footwear ──────────────────────────────────────────────────
  const Product(
    id: 'w_f1',
    name: "Satin Heeled Footwear",
    subtitle: "Evening Collection",
    price: 89.99,
    category: "Women",
    subCategory: "Footwear",
    imageUrl: "assets/images/woman/footwear/satin heeled footwear.webp",
    rating: 4.8,
    description: "Satin-finish heeled shoes with a sculptural block heel and pointed toe.",
    colors: ['#3D1F8C', '#1F2937'],
    sizes: ['36', '37', '38', '39', '40'],
  ),
  const Product(
    id: 'w_f2',
    name: "Symphony Wedding Mules",
    subtitle: "Bridal Collection",
    price: 74.99,
    category: "Women",
    subCategory: "Footwear",
    imageUrl: "assets/images/woman/footwear/Symphony Mules Comfortable White Wedding Heels.webp",
    badge: "NEW",
    rating: 4.9,
    description: "Elegant white mules designed for bridal comfort and style. Cushioned sole with a refined heel.",
    colors: ['#F9FAFB', '#E5E7EB'],
    sizes: ['36', '37', '38', '39', '40'],
  ),
  const Product(
    id: 'w_f3',
    name: "Black Stilettos",
    subtitle: "Power Dressing",
    price: 64.99,
    category: "Women",
    subCategory: "Footwear",
    imageUrl: "assets/images/woman/footwear/Women Black Solid Stilettos.webp",
    rating: 4.7,
    description: "Classic black stilettos with a sleek pointed toe. The ultimate power dressing shoe.",
    colors: ['#1F2937'],
    sizes: ['36', '37', '38', '39', '40', '41'],
  ),
  const Product(
    id: 'w_f4',
    name: "Women's Sandal Heels",
    subtitle: "Summer Luxe",
    price: 49.99,
    category: "Women",
    subCategory: "Footwear",
    imageUrl: "assets/images/woman/footwear/womens-sandals-shoes-womens.jpg",
    rating: 4.6,
    description: "Open-toe sandal heels in premium leather. A summer essential for effortless style.",
    colors: ['#D97706', '#9CA3AF'],
    sizes: ['36', '37', '38', '39', '40'],
  ),

  // ── Women › Outerwear ─────────────────────────────────────────────────
  const Product(
    id: 'w_o1',
    name: "Women's Outerwear Coat",
    subtitle: "Cashmere Blend",
    price: 149.99,
    category: "Women",
    subCategory: "Outerwear",
    imageUrl: "assets/images/woman/outware/women's outerwear coat.webp",
    rating: 4.9,
    description: "Premium cashmere blend coat with structured shoulders and a timeless silhouette.",
    colors: ['#3D1F8C', '#9CA3AF'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_o2',
    name: "Cashmere Shirt Jacket",
    subtitle: "Double Face",
    price: 174.99,
    category: "Women",
    subCategory: "Outerwear",
    imageUrl: "assets/images/woman/outware/Beige m├®lange Shirt Jacket in double face cashmere.webp",
    badge: "LIMITED",
    rating: 4.9,
    description: "Luxurious double-face cashmere shirt jacket in beige mélange. An investment piece.",
    colors: ['#D1D5DB', '#9CA3AF'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_o3',
    name: "Cashmere Waves Parka",
    subtitle: "20 Knots Edition",
    price: 199.99,
    category: "Women",
    subCategory: "Outerwear",
    imageUrl: "assets/images/woman/outware/Cashmere Waves and 20 KNOTS Parka.webp",
    rating: 4.8,
    description: "Statement cashmere parka with a wave-texture weave. Bold, warm, and unmistakably luxurious.",
    colors: ['#1F2937', '#6B7280'],
    sizes: ['XS', 'S', 'M', 'L'],
  ),
  const Product(
    id: 'w_o4',
    name: "Silk Cashmere Down Jacket",
    subtitle: "Oversized Fit",
    price: 159.99,
    category: "Women",
    subCategory: "Outerwear",
    imageUrl: "assets/images/woman/outware/Over-sized Down Jacket in Beige Silk and Cashmere.webp",
    rating: 4.7,
    description: "Oversized down jacket in beige silk-cashmere blend. Effortlessly chic for colder days.",
    colors: ['#FDE68A', '#D1D5DB'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  ),

  // ── Men › Suits ───────────────────────────────────────────────────────
  const Product(
    id: 'm_s1',
    name: "Grey Double Breasted Suit",
    subtitle: "2 Piece — Falcon Cut",
    price: 119.99,
    category: "Men",
    subCategory: "Suits",
    imageUrl: "assets/images/Man/SUITES/Grey Double Breasted 2 Piece Suit ÔÇô Falcon Suits.webp",
    rating: 4.8,
    description: "Sharp grey double-breasted suit with peak lapels and a tailored Falcon silhouette.",
    colors: ['#6B7280', '#1F2937'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'm_s2',
    name: "IRO Archives Wool Jacket",
    subtitle: "Archival Collection",
    price: 109.99,
    category: "Men",
    subCategory: "Suits",
    imageUrl: "assets/images/Man/SUITES/IRO ARCHIVES, WOOL SUIT JACKET.jpg",
    rating: 4.7,
    description: "Single-breasted wool suit jacket from the IRO archival collection. Refined and understated.",
    colors: ['#374151', '#1F2937'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'm_s3',
    name: "3 Piece Slim Fit Suit",
    subtitle: "Wedding Collection",
    price: 139.99,
    category: "Men",
    subCategory: "Suits",
    imageUrl: "assets/images/Man/SUITES/Mens Suits 3 Piece Slim Fit Suits for Men Wedding Sri Lanka.jpg",
    badge: "NEW",
    rating: 4.9,
    description: "Complete 3-piece slim fit suit crafted for weddings and formal events. Tailored to perfection.",
    colors: ['#1F2937', '#374151'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  ),
  const Product(
    id: 'm_s4',
    name: "Royal Black Velvet Suit",
    subtitle: "3 Piece Designer",
    price: 169.99,
    category: "Men",
    subCategory: "Suits",
    imageUrl: "assets/images/Man/SUITES/Royal Black Velvet 3 Piece Suit For Men Designer.webp",
    badge: "LIMITED",
    rating: 4.9,
    description: "Opulent black velvet 3-piece suit with satin lapels. The pinnacle of formal menswear.",
    colors: ['#111827'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),

  // ── Men › Shirts ──────────────────────────────────────────────────────
  const Product(
    id: 'm_sh1',
    name: "Check Printed Casual Shirt",
    subtitle: "Relaxed Fit",
    price: 29.99,
    category: "Men",
    subCategory: "Shirts",
    imageUrl: "assets/images/Man/SHIRTS/Men's Check Printed Casual Shirt.jpg",
    rating: 4.6,
    description: "Classic check-printed casual shirt in a relaxed fit. A wardrobe staple for everyday wear.",
    colors: ['#374151', '#D1D5DB'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  ),
  const Product(
    id: 'm_sh2',
    name: "Short Sleeve Designer Shirt",
    subtitle: "Summer Edition",
    price: 34.99,
    category: "Men",
    subCategory: "Shirts",
    imageUrl: "assets/images/Man/SHIRTS/Summer Short Sleeve Shirt Men's Design Sense Special.jpg",
    rating: 4.7,
    description: "Short sleeve shirt with a unique design sense. Statement summer wear.",
    colors: ['#FDE68A', '#D1D5DB'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'm_sh3',
    name: "Premium Formal Shirts",
    subtitle: "Tailored Collection",
    price: 39.99,
    category: "Men",
    subCategory: "Shirts",
    imageUrl: "assets/images/Man/SHIRTS/Types of Shirts for Men in Pakistan.webp",
    rating: 4.6,
    description: "Premium formal shirts in a range of classic cuts. Crafted for the modern professional.",
    colors: ['#F9FAFB', '#93C5FD', '#1F2937'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'm_sh4',
    name: "Tailored Silk Shirt",
    subtitle: "Lavender Haze",
    price: 44.99,
    category: "Men",
    subCategory: "Shirts",
    imageUrl: "assets/images/Man/SHIRTS/tailored silk shirt.webp",
    rating: 4.8,
    description: "100% silk shirt with mother-of-pearl buttons. Crafted for the discerning gentleman.",
    colors: ['#C4A8E0', '#1F2937'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),

  // ── Men › Shoes ───────────────────────────────────────────────────────
  const Product(
    id: 'm_sh5',
    name: "Chelsea Boots",
    subtitle: "Retro Genuine Leather",
    price: 69.99,
    category: "Men",
    subCategory: "Shoes",
    imageUrl: "assets/images/Man/Shoes/Men's Classic retro genuine leather Chelsea boots men Fashion.jpg",
    rating: 4.7,
    description: "Classic retro Chelsea boots in genuine full-grain leather. Timeless silhouette, modern finish.",
    colors: ['#1F2937', '#7B1D1D'],
    sizes: ['40', '41', '42', '43', '44'],
  ),
  const Product(
    id: 'm_sh6',
    name: "Handmade Loafers",
    subtitle: "Two Tone Calfskin",
    price: 79.99,
    category: "Men",
    subCategory: "Shoes",
    imageUrl: "assets/images/Man/Shoes/Men's handmade Pumps Slip on Loafers casual two tone men's loafer.jpg",
    rating: 4.8,
    description: "Handcrafted slip-on loafers in two-tone calfskin. The ultimate smart-casual shoe.",
    colors: ['#D97706', '#1F2937'],
    sizes: ['40', '41', '42', '43', '44'],
  ),
  const Product(
    id: 'm_sh7',
    name: "Men's Casual Shoes",
    subtitle: "Everyday Luxury",
    price: 49.99,
    category: "Men",
    subCategory: "Shoes",
    imageUrl: "assets/images/Man/Shoes/mens-shoes-mens-casual-shoes.jpg",
    rating: 4.5,
    description: "Premium casual shoes for everyday wear. Comfort and style in equal measure.",
    colors: ['#6B7280', '#1F2937'],
    sizes: ['40', '41', '42', '43', '44', '45'],
  ),
  const Product(
    id: 'm_sh8',
    name: "Oxford Dress Shoes",
    subtitle: "Calfskin Premium",
    price: 89.99,
    category: "Men",
    subCategory: "Shoes",
    imageUrl: "assets/images/Man/Shoes/oxford dress shoes.jpg",
    rating: 4.8,
    description: "Hand-welted Oxford shoes in full-grain calfskin. A timeless addition to any wardrobe.",
    colors: ['#1F2937', '#7B1D1D'],
    sizes: ['40', '41', '42', '43', '44'],
  ),

  // ── Men › Trousers ────────────────────────────────────────────────────
  const Product(
    id: 'm_tr1',
    name: "Smart Casual Ankle Pants",
    subtitle: "Cotton Solid",
    price: 39.99,
    category: "Men",
    subCategory: "Trousers",
    imageUrl: "assets/images/Man/trousers/Brand Cotton Solid Men's Smart Pants Spring Summer Casual Ankle.jpg",
    rating: 4.6,
    description: "Ankle-length cotton smart pants. Lightweight and versatile for spring and summer.",
    colors: ['#D1D5DB', '#374151'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'm_tr2',
    name: "Beige Lightweight Trousers",
    subtitle: "365 Collection",
    price: 44.99,
    category: "Men",
    subCategory: "Trousers",
    imageUrl: "assets/images/Man/trousers/Men's Beige 365 Trouser  Lightweight Trousers for Men.webp",
    rating: 4.7,
    description: "Year-round lightweight trousers in warm beige. Tailored comfort for any occasion.",
    colors: ['#FDE68A', '#D1D5DB'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'm_tr3',
    name: "Navy Fresco Wool Trousers",
    subtitle: "Slim Fit — 40 Colori",
    price: 59.99,
    category: "Men",
    subCategory: "Trousers",
    imageUrl: "assets/images/Man/trousers/Men's Navy Fresco Wool Slim Trousers - 40 Colori.webp",
    rating: 4.8,
    description: "Precision-cut slim fresco wool trousers in navy. Italian fabric, made to last a lifetime.",
    colors: ['#1E3A5F', '#374151'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'm_tr4',
    name: "Tailored Custom Trousers",
    subtitle: "Godwin Charli Fit",
    price: 69.99,
    category: "Men",
    subCategory: "Trousers",
    imageUrl: "assets/images/Man/trousers/Premium Men's Trousers , Tailored & Custom Fit Godwin Charli.webp",
    rating: 4.9,
    description: "Bespoke-quality tailored trousers with a custom Godwin Charli fit. Unmatched craftsmanship.",
    colors: ['#1F2937', '#6B7280'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  ),

  // ── Accessories › Bags ────────────────────────────────────────────────
  const Product(
    id: 'a_b1',
    name: "Luxury Backpack Bag",
    subtitle: "Urban Collection",
    price: 99.99,
    category: "Accessories",
    subCategory: "Bags",
    imageUrl: "assets/images/Accessories/Bag/BACKPACK BAG.webp",
    rating: 4.7,
    description: "Structured luxury backpack with premium hardware. Designed for the modern urbanite.",
    colors: ['#1F2937', '#4C1D95'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_b2',
    name: "Double Shoulder Backpack",
    subtitle: "MOOW Stylish",
    price: 79.99,
    category: "Accessories",
    subCategory: "Bags",
    imageUrl: "assets/images/Accessories/Bag/MOOW Stylish Double Shoulder Backpack.jpg",
    rating: 4.6,
    description: "Stylish double-shoulder backpack with compartments for the modern professional.",
    colors: ['#1F2937', '#6B7280'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_b3',
    name: "Canvas Travel Bag",
    subtitle: "Green Beige Edition",
    price: 59.99,
    category: "Accessories",
    subCategory: "Bags",
    imageUrl: "assets/images/Accessories/Bag/Travel bag canvas, green beige.jpg",
    rating: 4.5,
    description: "Durable canvas travel bag in green-beige. Practical luxury for the frequent traveller.",
    colors: ['#6B7280', '#D1D5DB'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_b4',
    name: "Women's Classic Hand Bag",
    subtitle: "Heritage Calfskin",
    price: 189.99,
    category: "Accessories",
    subCategory: "Bags",
    imageUrl: "assets/images/Accessories/Bag/Women's Classic Hand Bag.jpg",
    badge: "NEW",
    rating: 4.9,
    description: "Structured classic handbag in heritage calfskin with gold-tone hardware and monogram lining.",
    colors: ['#4C1D95', '#1F2937'],
    sizes: ['One Size'],
  ),

  // ── Accessories › Belts ───────────────────────────────────────────────
  const Product(
    id: 'a_bl1',
    name: "Dressy Leather Belt",
    subtitle: "1 Inch — Amish Made",
    price: 24.99,
    category: "Accessories",
    subCategory: "Belts",
    imageUrl: "assets/images/Accessories/Belts/Amish-Made Dressy Leather Belts - 1 inch wide, Amish-Made Belts - Lehman's.jpg",
    rating: 4.8,
    description: "Hand-crafted 1-inch dressy leather belt by Amish artisans. Exceptional quality and durability.",
    colors: ['#7B1D1D', '#1F2937'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'a_bl2',
    name: "Designer Women's Belt",
    subtitle: "ALDO Signature",
    price: 29.99,
    category: "Accessories",
    subCategory: "Belts",
    imageUrl: "assets/images/Accessories/Belts/Buy Designer Belts for Women Online  ALDO Shoes India.jpg",
    rating: 4.6,
    description: "Sleek designer belt for women with a polished buckle. A finishing touch to any outfit.",
    colors: ['#1F2937', '#D97706'],
    sizes: ['S', 'M', 'L'],
  ),
  const Product(
    id: 'a_bl3',
    name: "Genuine Leather Waist Belt",
    subtitle: "Stylish Design",
    price: 34.99,
    category: "Accessories",
    subCategory: "Belts",
    imageUrl: "assets/images/Accessories/Belts/MenÔÇÖs Genuine Leather Waist Belts with Stylish Designs.webp",
    rating: 4.7,
    description: "Premium genuine leather waist belt with an artistic buckle design. Bold and masculine.",
    colors: ['#7B1D1D', '#374151'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),
  const Product(
    id: 'a_bl4',
    name: "Double-Sided Men's Belt",
    subtitle: "Reversible Leather",
    price: 39.99,
    category: "Accessories",
    subCategory: "Belts",
    imageUrl: "assets/images/Accessories/Belts/Men's Belt Double-sided.jpg",
    badge: "LIMITED",
    rating: 4.7,
    description: "Versatile double-sided reversible leather belt. Two styles in one with a signature gold buckle.",
    colors: ['#1F2937', '#7B1D1D'],
    sizes: ['S', 'M', 'L', 'XL'],
  ),

  // ── Accessories › Scarves ─────────────────────────────────────────────
  const Product(
    id: 'a_sc1',
    name: "Custom Silk Scarf",
    subtitle: "Print on Silk",
    price: 29.99,
    category: "Accessories",
    subCategory: "Scarves",
    imageUrl: "assets/images/Accessories/Scarves/Custom Silk Scarf. Printing on Silk Scarf. Custom Scarves.jpeg",
    badge: "NEW",
    rating: 4.8,
    description: "Custom-printed pure silk scarf with hand-rolled edges. A statement piece for every ensemble.",
    colors: ['#6B21A8', '#D97706'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_sc2',
    name: "Pure Cashmere Scarf",
    subtitle: "Soft Pear — WoolOvers",
    price: 34.99,
    category: "Accessories",
    subCategory: "Scarves",
    imageUrl: "assets/images/Accessories/Scarves/Soft Pear Womens Premium Pure Cashmere Scarf WoolOvers UK.jpg",
    rating: 4.9,
    description: "Premium 100% pure cashmere scarf in a beautiful soft pear hue. Exceptionally warm and soft.",
    colors: ['#6B7280', '#D1D5DB'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_sc3',
    name: "Blanket Scarf",
    subtitle: "Travel Collection",
    price: 27.99,
    category: "Accessories",
    subCategory: "Scarves",
    imageUrl: "assets/images/Accessories/Scarves/The Best Blanket Scarves to Keep You Warm at 30,000 Feet Condé Nast Traveler.webp",
    rating: 4.7,
    description: "Oversized blanket scarf perfect for travel. Keeps you warm at altitude in unmatched style.",
    colors: ['#374151', '#D1D5DB'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_sc4',
    name: "Knitted Cable Scarf",
    subtitle: "Winter Collection",
    price: 24.99,
    category: "Accessories",
    subCategory: "Scarves",
    imageUrl: "assets/images/Accessories/Scarves/Winter Scarf for Women Cold Weather, Knitted Cable Sri Lanka.jpg",
    rating: 4.6,
    description: "Hand-knitted cable scarf for cold weather. Artisanal craftsmanship from Sri Lanka.",
    colors: ['#6B21A8', '#4B5563'],
    sizes: ['One Size'],
  ),

  // ── Accessories › Watches ─────────────────────────────────────────────
  const Product(
    id: 'a_w1',
    name: "Gold Bracelet Watch Set",
    subtitle: "2pcs Luxury Women",
    price: 74.99,
    category: "Accessories",
    subCategory: "Watches",
    imageUrl: "assets/images/Accessories/Watches/2pcs Set Watch Luxury Women Simple Dial Hollow Strap Fashion Gold Bracelet Quartz Wristwatch Student Ladies Watches Reloj Mujer.webp",
    badge: "NEW",
    rating: 4.7,
    description: "Elegant 2-piece women's watch set with hollow strap and gold bracelet quartz movement.",
    colors: ['#D97706', '#F9FAFB'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_w2',
    name: "Embellished Steel Watch",
    subtitle: "Haute Sauce Women",
    price: 59.99,
    category: "Accessories",
    subCategory: "Watches",
    imageUrl: "assets/images/Accessories/Watches/Haute Sauce Women Embellished Stainless Steel Watch.webp",
    rating: 4.6,
    description: "Stainless steel watch with embellished detailing. Glamorous and precise.",
    colors: ['#D97706', '#9CA3AF'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_w3',
    name: "Classic Men's Watch",
    subtitle: "Modern & Sporty",
    price: 129.99,
    category: "Accessories",
    subCategory: "Watches",
    imageUrl: "assets/images/Accessories/Watches/Mens Watches Classic, Modern & Sporty Styles.jpg",
    rating: 4.9,
    description: "Swiss-inspired automatic movement in classic and sporty styles. Sapphire crystal glass.",
    colors: ['#D97706', '#1F2937'],
    sizes: ['One Size'],
  ),
  const Product(
    id: 'a_w4',
    name: "Couple Leather Band Watch",
    subtitle: "Analog Quartz",
    price: 94.99,
    category: "Accessories",
    subCategory: "Watches",
    imageUrl: "assets/images/Accessories/Watches/Men's watch Couple Leather Band Analog Quartz Round Business Wrist Watch Man watches.jpg",
    rating: 4.8,
    description: "Round business wrist watch with leather band and analog quartz movement. Pairs beautifully.",
    colors: ['#1F2937', '#D97706'],
    sizes: ['One Size'],
  ),
];
final List<OrderHistoryItem> orderHistory = [
  const OrderHistoryItem(
    orderId: '#VA-92810',
    productName: 'Violet Atelier Gown',
    date: 'October 24, 2025',
    price: 189.99,
    status: 'DELIVERED',
    imageUrl: 'assets/images/woman/Dress/violet.jpg',
  ),

  const OrderHistoryItem(
    orderId: '#VA-88294',
    productName: 'Luxury Backpack Bag', 
    date: 'November 02, 2025',
    price: 74.99, 
    status: 'IN TRANSIT',
imageUrl: 'assets/images/Accessories/Bag/BACKPACK BAG.webp',  
  ),
];  
